spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates
    suffix: .html

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_address_book?Timezone=UTC&Unicode=true&characterEnconding=utf-8
    username: root
    password: 810601

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

server:
  tomcat:
    max-http-header-size: 81920